server:
  port: 9999

spring:
  profiles:
    active: swagger


management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    root: info
